# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://juntamilitar.netlify.app/"  # Include trailing slash
# title = "Clarity"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = "junta-militar"

DefaultContentLanguage = "pt"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
categoria = "categorias"
estiqueta = "etiquetas"
aeronave = "aeronaves"
guerra = "guerras"
fabricante = "fabricantes"
arma = "armas"
regiao = "regioes"

[outputs]
home = ["HTML", "RSS", "JSON"]